require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/jail_bookings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # JailBooking. As you add validations to JailBooking, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      JailBooking.create! valid_attributes
      get jail_bookings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      jail_booking = JailBooking.create! valid_attributes
      get jail_booking_url(jail_booking)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_jail_booking_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      jail_booking = JailBooking.create! valid_attributes
      get edit_jail_booking_url(jail_booking)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JailBooking" do
        expect {
          post jail_bookings_url, params: { jail_booking: valid_attributes }
        }.to change(JailBooking, :count).by(1)
      end

      it "redirects to the created jail_booking" do
        post jail_bookings_url, params: { jail_booking: valid_attributes }
        expect(response).to redirect_to(jail_booking_url(JailBooking.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JailBooking" do
        expect {
          post jail_bookings_url, params: { jail_booking: invalid_attributes }
        }.to change(JailBooking, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post jail_bookings_url, params: { jail_booking: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested jail_booking" do
        jail_booking = JailBooking.create! valid_attributes
        patch jail_booking_url(jail_booking), params: { jail_booking: new_attributes }
        jail_booking.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the jail_booking" do
        jail_booking = JailBooking.create! valid_attributes
        patch jail_booking_url(jail_booking), params: { jail_booking: new_attributes }
        jail_booking.reload
        expect(response).to redirect_to(jail_booking_url(jail_booking))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        jail_booking = JailBooking.create! valid_attributes
        patch jail_booking_url(jail_booking), params: { jail_booking: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested jail_booking" do
      jail_booking = JailBooking.create! valid_attributes
      expect {
        delete jail_booking_url(jail_booking)
      }.to change(JailBooking, :count).by(-1)
    end

    it "redirects to the jail_bookings list" do
      jail_booking = JailBooking.create! valid_attributes
      delete jail_booking_url(jail_booking)
      expect(response).to redirect_to(jail_bookings_url)
    end
  end
end
