require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/moo_tasks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MooTask. As you add validations to MooTask, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MooTask.create! valid_attributes
      get moo_tasks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      moo_task = MooTask.create! valid_attributes
      get moo_task_url(moo_task)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_moo_task_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      moo_task = MooTask.create! valid_attributes
      get edit_moo_task_url(moo_task)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MooTask" do
        expect {
          post moo_tasks_url, params: { moo_task: valid_attributes }
        }.to change(MooTask, :count).by(1)
      end

      it "redirects to the created moo_task" do
        post moo_tasks_url, params: { moo_task: valid_attributes }
        expect(response).to redirect_to(moo_task_url(MooTask.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MooTask" do
        expect {
          post moo_tasks_url, params: { moo_task: invalid_attributes }
        }.to change(MooTask, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post moo_tasks_url, params: { moo_task: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested moo_task" do
        moo_task = MooTask.create! valid_attributes
        patch moo_task_url(moo_task), params: { moo_task: new_attributes }
        moo_task.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the moo_task" do
        moo_task = MooTask.create! valid_attributes
        patch moo_task_url(moo_task), params: { moo_task: new_attributes }
        moo_task.reload
        expect(response).to redirect_to(moo_task_url(moo_task))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        moo_task = MooTask.create! valid_attributes
        patch moo_task_url(moo_task), params: { moo_task: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested moo_task" do
      moo_task = MooTask.create! valid_attributes
      expect {
        delete moo_task_url(moo_task)
      }.to change(MooTask, :count).by(-1)
    end

    it "redirects to the moo_tasks list" do
      moo_task = MooTask.create! valid_attributes
      delete moo_task_url(moo_task)
      expect(response).to redirect_to(moo_tasks_url)
    end
  end
end
